spring:
  application:
    name: rent-car-bot

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0


telegram:
  bots:
    enabled: true
    bots-list:
      bot:
        token: ${BOT_TOKEN}
        username: ${BOT_USERNAME}
        path: /webhook
        url: ${WEBHOOK_URL}

server:
  port: 8090

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

services:
  rent-car-service:
    url: http://localhost:8080