spring:
  application:
    name: Rent-Car-Bot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

telegram:
  bots:
    enabled: true
    bots-list:
      bot:
        token: ${BOT_TOKEN}
        username: ${BOT_USERNAME}
        path: /webhook
        url: ${WEBHOOK_URL}
server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka
  instance:
    hostname: localhost

