spring:
  application:
    name: Rent-Car-Bot

telegram:
  bots:
    enabled: true
    bots-list:
      mybot:
        token: ${BOT_TOKEN}
        username: ${BOT_USERNAME}
        path: "/webhook/mybot"

server:
  port: 8443                # HTTPS port (SSL talab qiladi)
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: your_password
    key-store-type: PKCS12
